presentation-small:
	pdflatex presentation-small.tex
presentation:
	pdflatex presentation.tex
clean:
	rm presentation.aux
	rm presentation.log
	rm presentation.nav
	rm presentation.out
	rm presentation.pdf
	rm presentation.snm
	rm presentation.toc
